class Spin < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user
  validates :content, presence: true, length: { maximum: 140 }
  validates :user_id, presence: true

  default_scope order('created_at DESC')

  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids  #followed_user_ids  is generated by - has_many :followed_users relationship in User model
    where("user_id IN (?) OR user_id = ?", followed_user_ids, user)  #user stands for user.id (rails convention) 
  end

end
